### ISSUE TITLE
Unable to store Job : 'DEFAULT.QueueMonitorJob', because one already exists with this identification.

### ISSUE THREAD

**Issue by gus-romero** [3wks/thundr#16]
Hey, I'm having this issue while running a Tomcat 7 Application on Elastic Beanstalk. This happens every time I try to deploy the app.

**App config**: ```64bit Amazon Linux 2016.09 v2.5.5 running Tomcat 7 Java 7```

**Java Stack trace**: 
```
ERROR thundr - Unable to store Job : 'DEFAULT.QueueMonitorJob', because one already exists with this identification.
2017-06-15T20:39:03.012Z ERROR [ThundrServlet] - Allocate exception for servlet ThundrServlet
org.quartz.ObjectAlreadyExistsException: Unable to store Job : 'DEFAULT.QueueMonitorJob', because one already exists with this identification.
	at org.quartz.simpl.RAMJobStore.storeJob(RAMJobStore.java:277) ~[quartz-2.1.7.jar:na]
	at org.quartz.simpl.RAMJobStore.storeJobAndTrigger(RAMJobStore.java:249) ~[quartz-2.1.7.jar:na]
	at org.quartz.core.QuartzScheduler.scheduleJob(QuartzScheduler.java:840) ~[quartz-2.1.7.jar:na]
	at org.quartz.impl.StdScheduler.scheduleJob(StdScheduler.java:250) ~[quartz-2.1.7.jar:na]
	at com.threewks.thundr.quartz.QuartzScheduler.scheduleJob(QuartzScheduler.java:184) ~[thundr-contrib-quartz-0.1.0.jar:na]
	at com.threewks.thundr.deferred.monitor.quartz.QuartzQueueMonitor.start(QuartzQueueMonitor.java:53) ~[thundr-contrib-deferred-0.1.0.jar:na]
	at com.threewks.thundr.deferred.DeferredModule.start(DeferredModule.java:50) ~[thundr-contrib-deferred-0.1.0.jar:na]
	at com.threewks.thundr.module.Modules.startNext(Modules.java:145) ~[thundr-1.1.1.jar:na]
	at com.threewks.thundr.module.Modules.runStartupLifecycle(Modules.java:97) ~[thundr-1.1.1.jar:na]
	at com.threewks.thundr.ThundrServlet.initModules(ThundrServlet.java:89) ~[thundr-1.1.1.jar:na]
	at com.threewks.thundr.ThundrServlet.init(ThundrServlet.java:64) ~[thundr-1.1.1.jar:na]
	at org.apache.catalina.core.StandardWrapper.initServlet(StandardWrapper.java:1269) ~[catalina.jar:7.0.75]
	at org.apache.catalina.core.StandardWrapper.loadServlet(StandardWrapper.java:1182) ~[catalina.jar:7.0.75]
	at org.apache.catalina.core.StandardWrapper.allocate(StandardWrapper.java:853) ~[catalina.jar:7.0.75]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:134) ~[catalina.jar:7.0.75]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:110) [catalina.jar:7.0.75]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:169) [catalina.jar:7.0.75]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103) [catalina.jar:7.0.75]
	at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:683) [catalina.jar:7.0.75]
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:962) [catalina.jar:7.0.75]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116) [catalina.jar:7.0.75]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:452) [catalina.jar:7.0.75]
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1087) [tomcat-coyote.jar:7.0.75]
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:637) [tomcat-coyote.jar:7.0.75]
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:316) [tomcat-coyote.jar:7.0.75]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_131]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_131]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-coyote.jar:7.0.75]
	at java.lang.Thread.run(Thread.java:745) [na:1.7.0_131]
```

**Comment by atomicleopard** [comment]
Hi Gus,

This issue seems to be caused by the kuhnza/thundr-contrib-deferred package, can you move the issue there please. @kuhnza Maybe you're able to recollect some of the workings of this library (looks to be thundr 1.1, thundr-conrib-deferred 0.1.0).

On the surface, it looks like maybe you're starting more than one ThundrServlet, or more than one DeferredModule (perhaps you have a default module and a named module?) - and that the QueueMonitorJob is being inserted twice when it really shouldn't be. I vaguely recall that this was designed to function in a distributed quartz deployment , so I'm guessing its resolvable with the right configuration.

**Comment by gus-romero** [comment]
Closing this and re opening as @atomicleopard suggested 
thx!!

**Comment by kuhnza** [comment]
Cheers @atomicleopard, have picked this up over in my repo.

**Comment by coldwarm7** [comment]
`scheduler.clear();`  scheduler init()
maybe can help you
